name: CI

on:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.md"
      - '!.github/workflows/ci.yml'
  push:
    branches:
      - main
      - jerry/test
    paths-ignore:
      - "**/*.md"
      - '!.github/workflows/ci.yml'
    tags-ignore:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  test-linux:
    name: Test Linux
    needs: [get-runner-labels]
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: x86_64-unknown-linux-gnu
      profile: "debug"
      runner: ${{ needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS }}
      test-diff: true

  test-release-linux:
    name: Test Release Linux
    needs: [get-runner-labels]
    uses: ./.github/workflows/reusable-build.yml
    strategy:
      fail-fast: false # Build and test everything so we can look at all the errors
      matrix:
        array:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
    with:
      target: ${{ matrix.array.target }}
      runner: ${{ needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS }}
